global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'diabetes-api'
    static_configs:
      - targets: ['diabetes-api:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']